export enum InvoiceStatus {
    SUBMITTED = 'SUBMITTED',
    GRN_IN_PROCESS = 'GRN_IN_PROCESS',
    GRN_COMPLETED = 'GRN_COMPLETED',
    GRN_REVERSED = 'GRN_REVERSED',
    UNDER_DISBURSEMENT_REVIEW = 'UNDER_DISBURSEMENT_REVIEW',
    DISBURSEMENT_IN_PROGRESS = 'DISBURSEMENT_IN_PROGRESS',
    RETURNED_TO_GRN = 'RETURNED_TO_GRN',
    REJECTED = 'REJECTED',
    PAYMENT_APPROVED = 'PAYMENT_APPROVED',
    PAID = 'PAID'
}