export enum WtgActivities {
    PRODUCTION = 'PRODUCTION',
    QUALITY = 'QUALITY',
    DISPATCH = 'DISPATCH',
    RECEIVING = 'RECEIVING',
    FOUNDATION = 'FOUNDATION',
    INSTALLATION = 'INSTALLATION',
    COMMISSIONING = 'COMMISSIONING'
}